2023-05-09 00:09:25,382 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 00:22:50,199 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 00:25:25,279 INFO    [projection_impl.py(create:17)] ImmutableMultiDict([('csrf_token', 'IjhiNDY0YmExM2RlYWFmZmMyYTFmNTg3MTk1MjE0Mjc0ZjM5MmQxNmUi.ZFl2rw.2oesy5KnFCZMsbWv9-h-jEasI9E'), ('projection-movie', '1'), ('projection-hall', '1'), ('projection-from', '2023-05-09'), ('projection-to', '2024-05-09'), ('projection-time', '12:45')])
2023-05-09 00:25:25,280 INFO    [base_facade.py(create:52)] create: {'id': None, 'hall_id': '1', 'movie_id': '1', 'date_from': '2023-05-09', 'date_to': '2024-05-09', 'time': '12:45'}
2023-05-09 00:27:16,042 INFO    [projection_impl.py(create:17)] ImmutableMultiDict([('csrf_token', 'IjhiNDY0YmExM2RlYWFmZmMyYTFmNTg3MTk1MjE0Mjc0ZjM5MmQxNmUi.ZFl2rw.2oesy5KnFCZMsbWv9-h-jEasI9E'), ('projection-movie', '1'), ('projection-hall', '2'), ('projection-from', '2023-05-09'), ('projection-to', '2024-05-09'), ('projection-time', '20:00')])
2023-05-09 00:27:16,043 INFO    [base_facade.py(create:52)] create: {'id': None, 'hall_id': '2', 'movie_id': '1', 'date_from': '2023-05-09', 'date_to': '2024-05-09', 'time': '20:00'}
2023-05-09 00:28:44,380 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 00:43:04,856 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 00:47:08,105 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 00:48:17,668 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:03:44,964 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:03:44,970 ERROR   [movie_impl.py(find:38)] can't compare datetime.datetime to datetime.date
Traceback (most recent call last):
  File "C:\Users\Markovic Milos\PycharmProjects\pythonProject\zavrsni-rad\main\service\impl\movie_impl.py", line 30, in find
    if p.date_to < datetime.now():
TypeError: can't compare datetime.datetime to datetime.date

2023-05-09 01:05:34,225 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:05:34,230 ERROR   [movie_impl.py(find:38)] can't compare datetime.datetime to datetime.date
Traceback (most recent call last):
  File "C:\Users\Markovic Milos\PycharmProjects\pythonProject\zavrsni-rad\main\service\impl\movie_impl.py", line 30, in find
    if p.date_to < datetime.combine(datetime.now().date(), time.min):
TypeError: can't compare datetime.datetime to datetime.date

2023-05-09 01:08:57,712 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:13:16,419 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:13:31,289 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:13:49,296 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:14:15,468 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:14:25,447 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:14:36,002 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:15:07,872 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:15:37,743 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:15:56,451 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:16:03,797 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:16:12,303 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:16:15,976 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:16:48,733 INFO    [base_facade.py(find:13)] value: 1, column: id
2023-05-09 01:16:53,574 INFO    [base_facade.py(find:13)] value: 1, column: id
